apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: {{ .Values.imageTag }}
  name: nginx-alpine
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
      - image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: nginx-alpine


# namespace: demo
# replica: 3
# imageRepository: nginx
# imageTag: "alpine"
# imagePullPolicy: IfNotPresent
# serviceType: ClusterIP
# servicePort: 8111
# configMapName: "version: alpine"
# resources:
#   limits:
#     cpu: 50m
#     memory: 256Mi