apiVersion: v1
kind: Service
metadata:
  name: nginx-alpine
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
    tag: {{ .Values.imageTag }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
    protocol: TCP
  selector:
    app: nginx
    tag: alpine