apiVersion: v1
name: techtrends
description: A Helm chart for the TechTrends application
keywords:
  - techtrends
version: 1.0.0
maintainers:
  - name: Sheldon Santos
    email: sheldon.santosdev@gmail.com
type: application
appVersion: "1.0.0"